version: "3"

volumes:
  redis:
    driver: "local"
  mongo:
    driver: "local"

services:
  mongo:
    #restart: on-failure:10
    image: mongo:latest
    #tty: true
    volumes:
      - './mongo:/data/db'
    ports:
      - '27017:27017'
    
#mongod --repair && mongod && 
  redis:
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  node:
    restart: always
    build:
      context: ./
    volumes:
      - ./:/project/node-test-server
    ports:
      - 3000:3000
      - 9229:9229
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
    command:
        sh -c 'npm i && npm run-script debug'